# Generated by Django 4.1.7 on 2023-04-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_is_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
