# Generated by Django 4.1.7 on 2023-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customuser_balance_userprofile_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Balance', max_digits=10),
        ),
    ]
